/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package paintbot;

import java.awt.*;
import java.awt.geom.*;
import java.util.Timer;
import java.util.*;
import javax.swing.*;

/**
 *
 * @author Brian
 */
public class Interface extends javax.swing.JFrame {
    
    private Kinematics kin = new Kinematics();
    private final Vector<Double> paintdots = new Vector();
    private final Vector<Color> color = new Vector();
    
    Timer timer = new Timer();
    TimerTask a1_pos_task;
    TimerTask a1_neg_task;
    TimerTask a2_pos_task;
    TimerTask a2_neg_task;
    TimerTask a3_pos_task;
    TimerTask a3_neg_task;
    
    Color selectedColor;

    /**
     * Creates new form Interface
     */
    public Interface() {      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        RobotFrame = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        axis1_negative = new javax.swing.JButton();
        axis1_positive = new javax.swing.JButton();
        axis2_negative = new javax.swing.JButton();
        axis2_positive = new javax.swing.JButton();
        axis3_negative = new javax.swing.JButton();
        axis3_positive = new javax.swing.JButton();
        paint_button = new javax.swing.JButton();
        cont_paint = new javax.swing.JCheckBox();
        reset = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PaintBot - Gig'em Robotics");

        RobotFrame = new RobotWorkspace();
        RobotFrame.setBackground(new java.awt.Color(255, 255, 255));
        RobotFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout RobotFrameLayout = new javax.swing.GroupLayout(RobotFrame);
        RobotFrame.setLayout(RobotFrameLayout);
        RobotFrameLayout.setHorizontalGroup(
            RobotFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        RobotFrameLayout.setVerticalGroup(
            RobotFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 733, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Sliding Axis");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Rotating Axis 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Rotating Axis 2");

        axis1_negative.setText("<-");
        axis1_negative.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                axis1_negativeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                axis1_negativeMouseReleased(evt);
            }
        });
        axis1_negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axis1_negativeActionPerformed(evt);
            }
        });

        axis1_positive.setText("->");
        axis1_positive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                axis1_positiveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                axis1_positiveMouseReleased(evt);
            }
        });
        axis1_positive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axis1_positiveActionPerformed(evt);
            }
        });

        axis2_negative.setText("<-");
        axis2_negative.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                axis2_negativeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                axis2_negativeMouseReleased(evt);
            }
        });
        axis2_negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axis2_negativeActionPerformed(evt);
            }
        });

        axis2_positive.setText("->");
        axis2_positive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                axis2_positiveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                axis2_positiveMouseReleased(evt);
            }
        });
        axis2_positive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axis2_positiveActionPerformed(evt);
            }
        });

        axis3_negative.setText("<-");
        axis3_negative.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                axis3_negativeMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                axis3_negativeMouseReleased(evt);
            }
        });
        axis3_negative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axis3_negativeActionPerformed(evt);
            }
        });

        axis3_positive.setText("->");
        axis3_positive.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                axis3_positiveMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                axis3_positiveMouseReleased(evt);
            }
        });
        axis3_positive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                axis3_positiveActionPerformed(evt);
            }
        });

        paint_button.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paint_button.setText("Paint");
        paint_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paint_buttonActionPerformed(evt);
            }
        });

        cont_paint.setText("Continuous Paint");

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jButton1.setText("Choose Color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RobotFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(reset)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(axis1_negative, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(axis1_positive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(axis2_negative, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(axis2_positive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(axis3_negative, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(42, 42, 42)
                                        .addComponent(axis3_positive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(paint_button, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(44, 44, 44))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(cont_paint)
                            .addGap(72, 72, 72)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(784, 784, 784)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RobotFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(axis1_negative, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(axis1_positive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(axis2_negative, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(axis2_positive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(axis3_negative, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(axis3_positive, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(paint_button, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cont_paint)
                        .addGap(45, 45, 45)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(reset)
                        .addGap(96, 96, 96))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Events to move robot arm
    
    private void axis1_negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis1_negativeActionPerformed
        kin.axis1_slide(false);
        RobotFrame.repaint();
    }//GEN-LAST:event_axis1_negativeActionPerformed

    private void axis1_positiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis1_positiveActionPerformed
        kin.axis1_slide(true);
        RobotFrame.repaint();
    }//GEN-LAST:event_axis1_positiveActionPerformed

    private void axis2_negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis2_negativeActionPerformed
        kin.axis2_rotate(false);
        RobotFrame.repaint();
    }//GEN-LAST:event_axis2_negativeActionPerformed

    private void axis2_positiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis2_positiveActionPerformed
        kin.axis2_rotate(true);
        RobotFrame.repaint();
    }//GEN-LAST:event_axis2_positiveActionPerformed

    private void axis3_positiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis3_positiveActionPerformed
        kin.axis3_rotate(true);
        RobotFrame.repaint();
    }//GEN-LAST:event_axis3_positiveActionPerformed

    private void axis3_negativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_axis3_negativeActionPerformed
        kin.axis3_rotate(false);
        RobotFrame.repaint();
    }//GEN-LAST:event_axis3_negativeActionPerformed
    
    //Event to paint dot
    private void paint_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paint_buttonActionPerformed
        paintdots.add(kin.a4_x - 5);
        paintdots.add(kin.a4_y - 5);
        color.add(selectedColor);
        RobotFrame.repaint();
    }//GEN-LAST:event_paint_buttonActionPerformed

    
    //Events to handle held down mouse
    private void axis1_negativeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis1_negativeMousePressed
        timer.scheduleAtFixedRate(a1_neg_task = new axis1_negTimerTask(), 400, 50);
    }//GEN-LAST:event_axis1_negativeMousePressed

    private void axis1_negativeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis1_negativeMouseReleased
        a1_neg_task.cancel();
    }//GEN-LAST:event_axis1_negativeMouseReleased

    private void axis1_positiveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis1_positiveMousePressed
        timer.scheduleAtFixedRate(a1_pos_task = new axis1_posTimerTask(), 400, 50);
    }//GEN-LAST:event_axis1_positiveMousePressed

    private void axis1_positiveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis1_positiveMouseReleased
        a1_pos_task.cancel();
    }//GEN-LAST:event_axis1_positiveMouseReleased

    private void axis2_negativeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis2_negativeMousePressed
        timer.scheduleAtFixedRate(a2_neg_task = new axis2_negTimerTask(), 400, 50);
    }//GEN-LAST:event_axis2_negativeMousePressed

    private void axis2_negativeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis2_negativeMouseReleased
        a2_neg_task.cancel();
    }//GEN-LAST:event_axis2_negativeMouseReleased

    private void axis2_positiveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis2_positiveMousePressed
        timer.scheduleAtFixedRate(a2_pos_task = new axis2_posTimerTask(), 400, 50);
    }//GEN-LAST:event_axis2_positiveMousePressed

    private void axis2_positiveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis2_positiveMouseReleased
        a2_pos_task.cancel();
    }//GEN-LAST:event_axis2_positiveMouseReleased

    private void axis3_negativeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis3_negativeMousePressed
        timer.scheduleAtFixedRate(a3_neg_task = new axis3_negTimerTask(), 400, 50);
    }//GEN-LAST:event_axis3_negativeMousePressed

    private void axis3_negativeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis3_negativeMouseReleased
        a3_neg_task.cancel();
    }//GEN-LAST:event_axis3_negativeMouseReleased

    private void axis3_positiveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis3_positiveMousePressed
        timer.scheduleAtFixedRate(a3_pos_task = new axis3_posTimerTask(), 400, 50);
    }//GEN-LAST:event_axis3_positiveMousePressed

    private void axis3_positiveMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_axis3_positiveMouseReleased
        a3_pos_task.cancel();
    }//GEN-LAST:event_axis3_positiveMouseReleased
    
    //reset action
    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        kin = new Kinematics();
        paintdots.clear();
        color.clear();
        RobotFrame.repaint();
    }//GEN-LAST:event_resetActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectedColor = JColorChooser.showDialog(this, "Pick a Color", Color.RED);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    
    //Class to draw robot arm and paint dots
    class RobotWorkspace extends JPanel{
        
        @Override
        public void paintComponent(Graphics g){
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D)g;
            
            //Draw robot arm and slide
            double xpoints[] = {kin.a1_x, kin.a2_x, kin.a3_x, kin.a4_x};
            double ypoints[] = {kin.a1_y, kin.a2_y, kin.a3_y, kin.a4_y};

            GeneralPath robotarm = new GeneralPath(GeneralPath.WIND_EVEN_ODD, xpoints.length);
            robotarm.moveTo(xpoints[0], ypoints[0]);
            for (int i = 1; i < xpoints.length; i++) {
                robotarm.lineTo(xpoints[i], ypoints[i]);
            }
            
            g2.setPaint(Color.gray);
            g2.fill(new Rectangle2D.Double(kin.base_x, kin.base_y, 300, 15));
            g2.setPaint(Color.black);
            g2.setStroke(new BasicStroke(5.0f));
            g2.draw(robotarm);
               
            if(cont_paint.isSelected()){
                paintdots.add(kin.a4_x - 5);
                paintdots.add(kin.a4_y - 5);
                color.add(selectedColor);
            }
            
            //Draw paint dots
            g2.setStroke(new BasicStroke(0f));
            for(int i = 0, j = 0; i < paintdots.size()-1; i+=2, j++){
                g2.setColor(color.elementAt(j));
                g2.fill(new Ellipse2D.Double(paintdots.elementAt(i), paintdots.elementAt(i+1), 10, 10));
            }
            
            
        }
        
    }
    
    //Classes to handle timers for button hold down repeat action   
    class axis1_posTimerTask extends TimerTask{
        @Override
        public void run(){
            kin.axis1_slide(true);
            RobotFrame.repaint();
        }
    }
    
    class axis1_negTimerTask extends TimerTask{
        @Override
        public void run(){
            kin.axis1_slide(false);
            RobotFrame.repaint();
        }
    }
    
    class axis2_posTimerTask extends TimerTask{
        @Override
        public void run(){
            kin.axis2_rotate(true);
            RobotFrame.repaint();
        }
    }
    
    class axis2_negTimerTask extends TimerTask{
        @Override
        public void run(){
            kin.axis2_rotate(false);
            RobotFrame.repaint();
        }
    }
    
    class axis3_posTimerTask extends TimerTask{
        @Override
        public void run(){
            kin.axis3_rotate(true);
            RobotFrame.repaint();
        }
    }
    
    class axis3_negTimerTask extends TimerTask{
        @Override
        public void run(){
            kin.axis3_rotate(false);
            RobotFrame.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RobotFrame;
    private javax.swing.JButton axis1_negative;
    private javax.swing.JButton axis1_positive;
    private javax.swing.JButton axis2_negative;
    private javax.swing.JButton axis2_positive;
    private javax.swing.JButton axis3_negative;
    private javax.swing.JButton axis3_positive;
    private javax.swing.JCheckBox cont_paint;
    private javax.swing.JButton jButton1;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton paint_button;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
